version: '3.8'

services:
  notification-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"  # Exponemos directamente el puerto 3001
    environment:
      - PORT=3001
      - NODE_ENV=production
    volumes:
      # Montar la carpeta de uploads del host en el contenedor
      - ${UPLOADS_PATH:-./uploads}:/app/uploads
      # Montar .env para usar las variables de entorno
      - ./.env:/app/.env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
