version: '3.8'

services:
  notification-api-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=development
      - BASE_UPLOAD_DIR=/app/uploads
    volumes:
      - ./src:/app/src  # Hot reload para desarrollo
      - ./uploads:/app/uploads
      - ./.env:/app/.env
      - ./package.json:/app/package.json
    command: node --inspect=0.0.0.0:9229 src/index.js  # Habilitar debugging
    restart: unless-stopped
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
